<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ArangoDBNetStandard" Version="3.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <ProjectReference Include="..\StudyGraph.Api\StudyGraph.Api.csproj" />
  </ItemGroup>

</Project>
